### ISSUE TITLE
Add Terraform fmt check as GitHub Action

### ISSUE THREAD

**Issue by danial-k** [voquis/terraform-aws-s3-encrypted#1]
Similar to this [github action](https://github.com/voquis/ubuntu-desktop-dev-setup/blob/main/.github/workflows/main.yml), we should create a [GitHub action](https://docs.github.com/en/actions/quickstart) based on the following GitLab CI config:

```yaml
stages:
  - Verify

Formatting:
  stage: Verify
  # Specify Docker image to execute scripts inside
  image:
    name: hashicorp/terraform:0.12.24
    entrypoint: [""]
  script:
    - terraform fmt -check -recursive -diff
```
